# ===============================
# DATABASE CONFIG (Neon PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-dry-wildflower-aq79gj6n.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XVOH9BPu3UbK
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=MySuperSecretKeyForJwtGeneration1234567890
jwt.expiration=86400000

# ===============================
# Swagger
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.requested-heartbeat=30

# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000