# ===============================
# DATABASE CONFIG (Render PostgreSQL)
# ===============================

spring.datasource.url=jdbc:postgresql://dpg-d7d11vosfn5c7381f1jg-a.oregon-postgres.render.com:5432/notifyguard_db
spring.datasource.username=notifyguard_db_user
spring.datasource.password=1vVGKA8rNxixYao4Cwqi5gzL7aZPA3qF

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=MySuperSecretKeyForJwtGeneration1234567890
jwt.expiration=86400000
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true